= lua-xlib
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:url-ci-github: https://github.com/sclu1034/lua-xlib/actions
:url-ci-badge-github: https://img.shields.io/github/workflow/status/sclu1034/lua-xlib/Lint%20&%20Test?style=flat-square
:url-license-badge: https://img.shields.io/badge/license-GPLv3-brightgreen?style=flat-square
:url-luarocks-badge: https://img.shields.io/luarocks/v/sclu1034/lua-xlib?style=flat-square
:url-luarocks-link: https://luarocks.org/modules/sclu1034/lua-xlib

image:{url-license-badge}[License]
ifdef::status[]
image:{url-ci-badge-github}[Build Status (GitHub Actions), link={url-ci-github}]
endif::[]
image:{url-luarocks-badge}[LuaRocks Package, link={url-luarocks-link}]

Lua bindings for https://x.org/releases/current/doc/libX11/libX11/libX11.html[XLib] and  https://www.x.org/wiki/libraries/libxrandr[libxrandr].

== Archived just 3 weeks after the first commit? What's going on?

When I started this project, I knew that XCB existed as a newer option to XLib. What I didn't know was the
extend of what XCB replaces in XLib's ecosystem.

The initial trigger for _lua-xlib_ was the need for XRandR bindings, with only adding as many XLib functions
as was needed to make the XRandR function usable. The fact that all of _libxrandr_'s calls are blocking didn't
feel right, but I figured that this might just be necessary for this protocol specifically.

Only when I casually browsed the XCB docs did I realize that it seems to be intended as a replacement for _all_ of the XLib ecosystem, including RandR, Render and other protocol additions. So, after learning that and the non-blocking nature of XCB, and reading the https://www.x.org/wiki/guide/xlib-and-xcb/[XLib vs XCB rational], I now consider XCB bindings to be a better fit for my use case.

Nonetheless, the things implemented in _lua-xlib_ so far should still work.

== Quick Start

Install _lua-xlib_ via LuaRocks:

[source,shell]
----
luarocks install lua-xlib
----

[source,lua]
----
local xlib = require("xlib")
local xrandr = require("xlib.xrandr")

local function find_by_size(list, w, h)
  for _, v in ipairs(list) do
    if v.width == w and v.height == h then
      return v
    end
  end
end

local display = xlib.XOpenDisplay()
local screen = xlib.DefaultScreen(display)
local root = xlib.RootWindow(display, screen)
local res = xrandr.XRRGetScreenResources(display, root)
local info = xrandr.XRRGetCrtcInfo(display, res, res.crtcs[1])
local mode = find_by_size(res.mode, 1600, 900)

xrandr.XRRSetCrtcConfig(
  display,
  res,
  res.ctcs[1]
  info.timestamp,
  info.x,
  info.y,
  mode.id,
  info.rotation,
  info.outputs
)
----
