name: Lint & Test

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

env:
  CI: true
  DEBIAN: noninteractive

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        lua_version: ['5.1.5', '5.2.4', '5.3.6', '5.4.4']
    steps:
      - name: Install dependencies
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libx11-dev \
            libxrandr-dev \
            libreadline-dev

      - name: Install Lua ${{ matrix.lua_version }}
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        run: |
          curl -R -O http://www.lua.org/ftp/lua-${{ matrix.lua_version }}.tar.gz
          tar -xzf lua-${{ matrix.lua_version }}.tar.gz
          cd lua-${{ matrix.lua_version }}/src
          make -j$(nproc) all MYLIBS="-Wl,-E -ldl -lreadline -lhistory -lncurses" MYCFLAGS="-DLUA_USE_LINUX -DLUA_USE_READLINE -fPIC"
          cd ..
          sudo make install

      - name: Install LuaRocks
        run: |
          wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
          tar zxpf luarocks-3.8.0.tar.gz
          cd luarocks-3.8.0
          ./configure --with-lua-include=/usr/local/include
          make -j$(nproc)
          sudo make install

      - name: Install Busted
        run: sudo luarocks install busted

      - uses: actions/checkout@v3.0.2

      - name: Build
        run: |
          cmake -S . -B build -DCI=ON
          cd build
          make -j$(nproc) xlib

      - name: Run tests
        run: xvfb-run busted --config-file=.busted.lua --output=TAP

  rock:
    runs-on: ubuntu-20.04
    needs: [test]
    strategy:
      fail-fast: false
      matrix:
        lua_version: ['5.1.5', '5.2.4', '5.3.6', '5.4.4']
    steps:
      - name: Install dependencies
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libx11-dev \
            libxrandr-dev \
            libreadline-dev

      - name: Install Lua ${{ matrix.lua_version }}
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        if: matrix.lua_version != 'luajit'
        run: |
          curl -R -O http://www.lua.org/ftp/lua-${{ matrix.lua_version }}.tar.gz
          tar -zxf lua-${{ matrix.lua_version }}.tar.gz
          cd lua-${{ matrix.lua_version }}/src
          make -j$(nproc) all MYLIBS="-Wl,-E -ldl -lreadline -lhistory -lncurses" MYCFLAGS="-DLUA_USE_LINUX -DLUA_USE_READLINE -fPIC"
          cd ..
          sudo make install

      - name: Install LuaRocks
        run: |
          wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
          tar zxpf luarocks-3.8.0.tar.gz
          cd luarocks-3.8.0
          ./configure --with-lua-include=/usr/local/include
          make -j$(nproc)
          sudo make install

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - uses: actions/checkout@v3.0.2

      - name: Install tools
        run: |
          sudo luarocks install ldoc
          sudo luarocks install lua-discount
          npm install -g sass

      - name: Make rock
        run: luarocks --local make rocks/lua-xlib-scm-3.rockspec
