name: Lint & Test

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

env:
  CI: true
  DEBIAN: noninteractive

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install LuaCheck
        run: luarocks install luacheck

      - name: Run checks
        run: make check LUA_VERSION=${{ matrix.lua_version }}

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        lua_version: ['5.1', '5.2', '5.3', '5.4', 'luajit']
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install Busted
        run: luarocks install busted

      - name: Install dependencies
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxrandr-dev

      - name: Build
        run: make build

      - name: Run tests
        run: make test LUA_VERSION=${{ matrix.lua_version }}

  rock:
    runs-on: ubuntu-20.04
    needs: [check, test]
    strategy:
      fail-fast: false
      matrix:
        lua_version: ['5.1', '5.2', '5.3', '5.4']
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install tools
        run: |
          luarocks install ldoc
          luarocks install lua-discount
          npm install -g sass

      - name: Install dependencies
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxrandr-dev

      - name: Make rock
        run: make rock LUA_VERSION=${{ matrix.lua_version }}
