name: Deploy docs

on:
  push:
    branches: ['master']

env:
  DEBIAN: noninteractive

jobs:
  deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      # LDoc in packages is built against Lua 5.2, so I need to use that
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libx11-dev \
            libxrandr-dev \
            lua5.2 \
            liblua5.2-dev \
            lua-ldoc \
            lua-discount
          npm install --location=global sass

      - name: Generate documentation
        run: |
          cmake -S . -B build -DCI=ON
          cd build
          make docs

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build/doc
